SQLALCHEMY_DATABASE_URI = 'sqlite:///base.sqlite3'
# SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = 'password'
SECURITY_PASSWORD_SALT = 'salt'
SECURITY_TOKEN_AUTHENTICATION_HEADER = 'Authentication-Token'
SECURITY_PASSWORD_HASH = 'bcrypt'
WTF_CSRF_ENABLED = False
SECURITY_PASSWORD_SINGLE_HASH = False

CACHE_TYPE = "RedisCache"
CACHE_REDIS_URL = "redis://localhost:6379/0"
CACHE_DEFAULT_TIMEOUT = 300
DEB0UG = False

# Upload Files Conf
UPLOAD_FOLDER = 'static/export/'
EMAIL_TEMPLATE = 'templates/'
PDF_FOLDER = 'static/pdf/'

# Celery
CELERY_BROKER_URL = "redis://localhost:6379/1"
CELERY_RESULT_BACKEND = "redis://localhost:6379/2"

# JWT TOKEN EXPIRATION
JWT_ACCESS_TOKEN_EXPIRES = 3600
JWT_IDENTITY_CLAIM = 'email'